web_chat/chat/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('', views.auth_check, name='start'),
    path('me/', views.dashboard, name='dashboard'),  
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('me/create-dialogue/<int:user_id>', login_required
(views.CreateDialogueView.as_view()), name='create dialogue'),
    path('me/dialogue/<int:chat_id>', login_required
(views.MessagesView.as_view()), name='l'),
]

web_chat/web_chat/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
]

web_chat/chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
 
class Chat(models.Model):
    members = models.ManyToManyField(User)
    check_sum = models.IntegerField()
    
class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    is_readed = models.BooleanField(default=False)
    
    class Meta:
        ordering=['pub_date']
 
    def __str__(self):
        return self.message

web_chat/chat/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Message

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password_repeat = forms.CharField(label='Repeat password',
                                      widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username',)
    
    def clean_password_repeat(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password_repeat']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password_repeat']

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {'message': ""}

web_chat/chat/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.views import View

from .models import Chat, Message
from .forms import LoginForm, UserRegistrationForm, MessageForm

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/chat/me')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'chat/login.html', {'form': form})

@login_required
def user_logout(request): 
    logout(request)
    return render(request, 'chat/logged_out.html')

def auth_check(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/chat/me')
        else:
            return redirect('/chat/login')

@login_required
def dashboard(request):
    if request.method == 'GET':

        username = request.GET.get('q')
        if username is not None:
            if username == request.user.username:
                return HttpResponse('You have entered your username!')
            try:
                user = User.objects.get(username=username)
                return render(request, 'chat/found_user.html', {'user_id': user.id, 'username': username})
            except User.DoesNotExist:
                return HttpResponse('User isn\'t found')

    return render(request, 'chat/dashboard.html')

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return redirect('/chat/login')
    else:
        user_form = UserRegistrationForm()
    return render(request, 'chat/register.html', {'user_form': user_form})

class MessagesView(View):
    def get(self, request, chat_id):
        try:
            chat = Chat.objects.get(id=chat_id)
            if request.user in chat.members.all():
                chat.message_set.filter(is_readed=False).exclude(author=request.user).update(is_readed=True)
            else:
                chat = None
        except:
            chat = None
        
        form = MessageForm()
        return render(
            request,
            'chat/user_chat.html',
            {
                'chat': chat,
                'form': form,
            }
        )

    def post(self, request, chat_id):
        form = MessageForm(request.POST)
        if form.is_valid():
            user_message = Message()
            user_message.message = form.cleaned_data['message']
            user_message.chat = Chat.objects.get(id=chat_id)
            user_message.author = request.user
            user_message.save()
        return redirect('/chat/me/dialogue/{0}'.format(chat_id), {'chat_id', chat_id})


class CreateDialogueView(View):
    def get(self, request, user_id):
        chk_sum = request.user.id + user_id
        
        chats = Chat.objects.filter(check_sum=chk_sum)

        if chats.count() == 0:
            chat = Chat(check_sum=chk_sum)
            chat.save()
            chat.members.add(request.user)
            user = User.objects.get(id=user_id)
            chat.members.add(user)
            chat.save()
        else:
            chat = chats.first()
        return redirect('/chat/me/dialogue/{0}'.format(chat.id))

web_chat/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <span class="logo">WebChat</span>
      <span class="user">
        {% if request.user.is_authenticated %}
          Hello {{ request.user.username }},
          <a href="{% url "logout" %}">Logout</a>
        {% else %}
          <a href="{% url "login" %}">Log-in</a>
        {% endif %}
      </span>
    </div>
    <div id="content">
     {% block content %}
     {% endblock %}
     </div>
  </body>
</html>

web_chat/templates/chat/dashboard.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  {% load bootstrap3 %}
  <form action="{% url 'dashboard' %}" class="navbar-form navbar-left" method="get">
      <div class="input-group">
          <input id="search" name="q" type="text" class="form-control" placeholder="Поиск">
          &nbsp;
          <span class="input-group-btn">
              <button type="submit" class="btn">Search</button>
          </span>
      </div>
  </form>

  <hr>

  <div class="panel">
        {% load tz %}
        {% if chats.count == 0 %}
            <div class="panel panel-body">{% trans "Нет ни одного начатого диалога" %}</div>
        {% endif %}
    </div>
{% endblock %}

web_chat/templates/chat/found_user.html
{% extends "base.html" %}

{% block title %}Found user{% endblock %}

{% block content %}
    {{ username }} 
    <a href="{% url 'create dialogue' user_id %}">Start dialogue</a>
{% endblock %}

web_chat/templates/chat/logged_out.html
{% extends "base.html" %}

{% block title %}
    Logged out
{% endblock %}

{% block content %}
    <h1>
        Logged out
    </h1>
    <p>
        You have been successfully logged out.
        You can <a href="{% url "login" %}">log-in again</a>.
    </p>
{% endblock %}

web_chat/templates/chat/login.html
{% extends "base.html" %} 

{% block title %}
    Log-in
{% endblock %} 

{% block content %}
    <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
    <form method="POST">
        {{ form.as_p }} {% csrf_token %}
        <p><input type="submit" value="Log in" /></p>
    </form>

    <a href="{% url "register" %}">Not with us? Register now...</a>
{% endblock %}

web_chat/templates/chat/message.html
{% load tz %}
<div class="list-group-item {% if not message_item.is_readed %}unreaded{% endif %}">
    <div class="reply-body">
        <ul class="list-inline">
            <li class="drop-left-padding">
                <strong class="list-group-item-heading">{{ message_item.author.username }}</strong>
            </li>
            <li class="pull-right text-muted"><small>{{ message_item.pub_date|utc }}</small></li>
        </ul>
        <div>{{ message_item.message|safe }}</div>
    </div>
</div>

web_chat/templates/chat/register.html
{% extends "base.html" %} 

{% block title %}
    Create an account
{% endblock %} 

{% block content %}
    <h1>Create an account</h1>
    <p>Please, sign up using the following form:</p>
    <form method="POST">
      {% csrf_token %}
      <div class="fieldWrapper">
        {{ user_form.username.errors }}
        <label for="id_username">Username:</label>
        {{ user_form.username }}
      </div>
      <div class="fieldWrapper">
        {{ user_form.password.errors }}
        <label for="id_password">Password:</label>
        {{ user_form.password }}
      </div>
      <div class="fieldWrapper">
        {{ user_form.password_repeat.errors }}
        <label for="id_password_repeat">Repeat password:</label>
        {{ user_form.password_repeat }}
      </div>
    <p><input type="submit" value="Create my account" /></p>
    </form>
{% endblock %}

web_chat/templates/chat/user_chat.html
{% extends "base.html" %} 

{% load i18n %}

{% block title %}
    chat
{% endblock %} 

{% block content %}
    {% if not chat %}
        <div class="panel panel-body">
            {% trans "Невозможно начать беседу. Не найден пользователь или вы не имеете доступа к данной беседе." %}
        </div>
    {% else %}
        {% load tz %}
        {% if chat %}
            <div id="messages" class="panel">
                <div id="innerMessages">
                    {% for message in chat.message_set.all %}
                        {% include 'chat/message.html' with message_item=message %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div id="message_form">
            <form id="message-form" class="panel panel-body" method="post" >
                {% load bootstrap3 %}
                {% csrf_token %}
                <div class="fieldWrapper">
                    {{ form.message.errors }}
                    {{ form.message }}
                </div>
                <button type="submit" class="btn btn-default btn-sm" onclick="return ETextEditor.validateForm('message-form')"><span class="ico ico-comment"></span>{% trans "Отправить" %}</button>
            </form>
        </div>
    {% endif %}
{% endblock %}